name: CI

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mhils/workflows/checkout@v11
      - uses: mhils/workflows/setup-python@v11
      - uses: mhils/workflows/setup-uv@v11
      - run: uv run tox
